version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www
      - ./default.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - '8777:80'
    working_dir: /var/www
  php:
    build:
      context: .
      dockerfile: php.docker
    volumes:
      - ./src:/var/www
    working_dir: /var/www
